### ISSUE TITLE
Works only on Chrome

### ISSUE THREAD

**Issue by pieciaq** [wilddeer/stickyfill#42] opened 2016-04-20 08:14 UTC
hello,
i've some problem. I run stickyfill from command `$('.sticky').Stickyfill();` in global js file, but it's start running only in Chrome. When I install it in first time it's working fine in all browsers. What happend? I reinstall that and have still the same problem.

How can i run it on every browser?

**Comment by luixxiul** [comment] 2016-04-29 03:22
Same here. It stopped working suddenly on Firefox.

**Comment by mattez** [comment] 2016-05-14 16:23
Hi guys. Firefox [supports CSS *postion:sticky*](http://caniuse.com/#feat=css-sticky). Far as I know this polyfill is clever and runs only on browsers which not support CSS *postion:sticky* natively.
So it not runs in Firefox and you have to call *postion:sticky* by your CSS. Do you have something like this in your CSS?
```css
.sticky {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
}
```
(it is mentioned in README file here)

**Comment by caffodian** [comment] 2016-05-25 06:34
Was anyone able to figure out what was going on here?

I've run into a case where the polyfilled sticky works on Chrome & IE11, but oddly, the browsers that have native implementations don't seem to actually stick, although they recognize the css value.

**Comment by caffodian** [comment] 2016-05-25 06:47
I haven't fully reproduced it yet, but from dragging elements around, this different behaviour only appears to happen when putting a sticky element inside a Bootstrap nav tab.  About to pass out, but thought I'd leave that note here in case anyone else had been looking into it.

**Comment by caffodian** [comment] 2016-05-25 18:09
I wanted to update on my case.  I doubt it's the same issue the OP ran into and it's a pretty weird interaction with BS2 navtabs in particular.

Basically from here (there is an actual draft spec somewhere that says the same thing, but in less readable terms) http://www.coreyford.name/files/position-sticky-presentation/

> The box's position depends on its containing block (established as for position:static) as well as its scrolling container, defined by the nearest ancestor in the same document with a computed value for 'overflow-x' or 'overflow-y' other than 'visible', or the viewport if no such ancestor exists.

This polyfill doesn't appear to support the nearest ancestor case.

A quirk of Bootstrap 2 is that it sets overflow: auto on the nav tab content.  In the native case, this effectively means the sticky element will try to stick to the top of the nav tab, which will never acutally 'scroll" the sticky element out of view.

I forked some gists to show the issue:

BS2 fiddle: https://jsfiddle.net/caffodian/6t9hjuca/1/

BS2 with stickyfill (use a non-FF or Safari browser and compare it) https://jsfiddle.net/caffodian/8n1s3fnr/2/

BS3: https://jsfiddle.net/caffodian/4t3n7ykg/2/ (magically "works" as intended, but that's because BS3 stops setting the overflow on the tab content)

**Comment by wilddeer** [comment] 2016-05-26 07:46
@caffodian this case is described in readme https://github.com/wilddeer/stickyfill#pro-tips

**Comment by jimsontan** [comment] 2016-10-27 02:25
Same problem here. Works only on my chrome browser even i already put this in my css.

.sticky {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
}

**Comment by Deriohig** [comment] 2017-01-09 15:46
If your having trouble getting the css to work in Safari, Firefox, etc... you can modify the following in the stickyfill.js file 

 var prefixes = ['', '-webkit-', '-moz-', '-ms-'],
        block = document.createElement('div');

    for (var i = prefixes.length - 1; i >= 0; i--) {
        try {
            block.style.position = prefixes[i] + 'sticky';
        }
        catch(e) {}
        if (block.style.position != '') {
            seppuku(); //remove this
        }
    }

All you have to do is remove seppuku(); which kills the JS in browsers that already support position: sticky. 

Hope that helps.

**Comment by wilddeer** [comment] 2017-10-03 11:25
Sorry for the late reply, didn’t have much time to work on my personal projects lately.

Closing this. Please reopen this issue or create a new one if you still have problems. Provide a live reproduction of your problem (link to your website or codepan/jsfiddle/etc).

**Closed by wilddeer** 2017-10-03 11:25 UTC
